---
title: "2-5 邏輯運算"
author: "kbjiyu"
date: "2021/10/06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 2-5-1 邏輯值(布林值)

```{r}
bool_1 <- TRUE
bool_2 <- T
bool_3 <- FALSE
bool_4 <- F

class(bool_1)
is.logical(bool_1)

```


## 2-5-2 邏輯判斷

- 大於/小於/等於
  - A > B  : A大於B。
  - A < B  : A小於B。
  - A <= B : A小於等於B。
  - A >= B : A大於等於B。
  - A == B : A等於B。
  - A != B : A不等於B。
- 在其中
  - A %in% B : 判斷 A 是否在 B 之中。
- 交集/聯集
  - &  : 且(交集)，適用於向量式的邏輯判斷。
  - |  : 或(聯集)，適用於向量式的邏輯判斷。
  - && : 且(交集)，只採用向量中的第一個值做整串向量的邏輯判斷。
  - || : 或(聯集)，只採用向量中的第一個值做整串向量的邏輯判斷。
- 向量判斷用函數
  - which: 挑選出符合之元素。
  - any: 是否其中有任一元素符合條件。
  - all: 是否所有元素皆符合條件。


### 基礎判斷

``` {r 基礎判斷}

# 基礎判斷
5 > 6 # FALSE
6 >= 6 # TRUE
7 <= 10 # TRUE
10 != 11 # TRUE
5 == 5L # TRUE
T # TRUE
!T # FALSE
!!T # TRUE
!!!T # FALSE
```

### 怪用法

```{r 怪用法}
# 注意一些怪用法(避免這樣的比較出現)
"A" < "B" # TRUE
"A" <= "AA" # TRUE
5 <= "1" # FALSE
5 <= "06" # FALSE
5 <= "6" # TRUE
1 == T # TRUE
0 == F # TRUE

```

### 在其中

```{r 在其中}
c(1:6)
1 %in% c(1:6) # TRUE
!(1 %in% c(1:6)) # FALSE

```

### 交集

```{r 交集}
T & T # T
T & F # F
F & T # F
F & F # F

(c(1,2,3) >= 3) & c(T, T, T) # FALSE FALSE  TRUE
(c(1,2,3) >= 3) && c(T, T, T) # FALSE

```

### 聯集

```{r 聯集}
T | T # T
T | F # T
F | T # T
F | F # F

(c(1,2,3) >= 3) | c(T, T, T) # TRUE TRUE TRUE
(c(1,2,3) >= 3) || c(T, T, T) # TRUE

```

### 向量判斷用函數

```{r 向量判斷用函數}

any(c(1,2,3,4) > 4) # FALSE
any(c(1: 5) > 4) # TURE
which(c(1: 11) > 4) # 5  6  7  8  9 10 11 
all(c(1: 11) > 4) # FALSE

```

## 課堂練習
請在執行程式碼前，判斷以下邏輯值為何

### 練習
```{r}

# Q1
T == TRUE

# Q2
1 >= 2

# Q3
(5>3) & (1>2)

# Q4
T & T & F

# Q5
(T | F) | (F | F)

# Q6
c(1, 2, 3) > 2

# Q7
any(c(1, 2, 3) >2)

# Q8
all(c(2, 3, 4) < 3)

# Q9
10 != 12

# Q10
!(6 %in% c(1:6))
```
