---
title: "R Markdown 範例"
author: "kbjiyu"
date: "2021/10/06"
output:
  html_document: default
  pdf_document: default
---

## 全局設定

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  fig.width=12, 
  fig.height=8  
)
```

## 1 檔案說明

> 這是一份 **R Markdown** 檔案(.Rmd)。

- Markdown是一種輕量級標記式語言，能快速做文字排版。
  - 關於Markdown(.md)，可參考 <https://markdown.tw/>。
  - 關於R Markdown，可參考<http://rmarkdown.rstudio.com>。
- 點擊 **Knit** 按鈕，可將文件輸出為 HTML, PDF, Word。

## 2 區塊(Chunk)

### 2.1 Hello World!

-   You can embed an R code chunk like this:

```{r}
# 第一行程式碼
print("Hello World!")

```

### 2.2 輸出程式碼與結果

```{r cars}
summary(cars)

```

### 2.3 輸出結果，但不顯示程式碼

- echo=FALSE

```{r pressure, echo=FALSE}
plot(pressure)
```

### 2.4 輸出程式碼，但不顯示結果

- eval=FALSE

```{r eval=FALSE}
dim(iris)
```

### 2.5 美化表格

- 參考 [kable](https://bookdown.org/yihui/rmarkdown-cookbook/kable.html)。

```{r}
data <- iris[1:5, ]

knitr::kable(data, caption = "Table with kable", align = "lccrr", digits = 2)
```

```{r}
data <- iris[1:5, ]

data
```

### 2.6 於markdown文字內使用變數

```{r}
x <- 1

```


- 變數x的值為: `r x`
- 2+2 = `r 2+2`